name: Generate Stats

on:
  schedule:
    - cron: "0 */12 * * *" # roda a cada 12 horas
  workflow_dispatch: # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.PAT_1 }}
